### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by zhouyun-zoe**

### CODE REVIEW

**Review by kaikai1024 — COMMENTED** [review]
website/i18n/en.json

**Comment by zhouyun-zoe** [comment]
> website/i18n/en.json

fixed

**Review by kaikai1024 — DISMISSED** [review]

**Comment by zhouyun-zoe** [comment]
@kaikai1024 rebased. Need to review again.

**Comment by kaikai1024** [comment]
> @kaikai1024 rebased. Need to review again.

Seems the rebase does not succeed. check the `files change`

**Comment by zhouyun-zoe** [comment]
> > @kaikai1024 rebased. Need to review again.
> 
> Seems the rebase does not succeed. check the `files change`

rebased again.

**Review by kaikai1024 — APPROVED** [review]

**Pull request merged**
