### PR TITLE
Add network.toml description for network@v0.24.0

### PR DESCRIPTION
**Pull request by leeyr338**
Add network.toml description for network@v0.24.0

### CODE REVIEW

**Review by kaikai1024 — COMMENTED** [review]
Just the version-0.24.0 folder

**Comment by leeyr338** [comment]
> Just the version-0.24.0 folder

Yes, `enable_discovery = true` only after v0.24.0.

**Comment by kaikai1024** [comment]
I mean just fix the `version-0.24.0` folder. 
It's no need to change the `translated_docs` folder.

**Comment by leeyr338** [comment]
> I mean just fix the `version-0.24.0` folder.
> It's no need to change the `translated_docs` folder.

Okay, I got this!

**Review by kaikai1024 — APPROVED** [review]

**Pull request merged**
