### PR TITLE
修改了组管理文档中一些英文释义的错误

### PR DESCRIPTION
**Pull request by luotuo29**
修改了deleteAccounts中的address[]和很多接口中address的释义

### CODE REVIEW

**Review by leeyr338 — DISMISSED** [review]

**Review by kaikai1024 — DISMISSED** [review]
tips: the commits should use English.

**Comment by luotuo29** [comment]
> tips: the commits should use English.

Should I close this pr. then change commits' message to english?

**Comment by kaikai1024** [comment]
> Should I close this pr. then change commits' message to english?

No. you can use `git rebase -i master`, then `reword` or `fixup`, then `git push -f xx xx`

**Comment by luotuo29** [comment]
> > Should I close this pr. then change commits' message to english?
> 
> No. you can use `git rebase -i master`, then `reword` or `fixup`, then `git push -f xx xx`

I changed

**Review by kaikai1024 — APPROVED** [review]

**Review by leeyr338 — APPROVED** [review]

**Pull request merged**
