### PR TITLE
Add ui func

### PR DESCRIPTION
**Pull request by Keith-CY**
- replace searchbar placeholder
- set color of navbar items to black
- add edit on github button

### CODE REVIEW

**Comment by Keith-CY** [comment]
The <kbd>edit on Github</kbd> button was add at all pages belong to `zh-CN/cita/`, and there's one page at `zh-CN/welcome`, should it be a part of `cita docs` and tagged with <kbd>edit on Github</kbd>?

**Comment by zhouyun-zoe** [comment]
The <kbd>Edit</kbd> button is supposed to add at all pages under 'zh-CN', please refer to official Docusaurus docs: https://docusaurus.io/docs/en/installation

**Comment by Keith-CY** [comment]
> The Edit button is supposed to add at all pages under 'zh-CN', please refer to official Docusaurus docs: https://docusaurus.io/docs/en/installation

IMO, the page `zh-CN/welcome` should refer to `citahub docs`, not `cita docs`.

**Comment by zhouyun-zoe** [comment]
Totally agree with you

**Pull request merged**
