### PR TITLE
update chain-config and error format

### PR DESCRIPTION
**Pull request by boundless-forest**
#178

### CODE REVIEW

**Comment by kaikai1024** [comment]
Please post a preview

**Comment by boundless-forest** [comment]
> Please post a preview

Now, I can not run in local environment, i am trying ....

**Comment by boundless-forest** [comment]
Sorry, I could not load the latest modification effect in my local env. Maybe some problems with our website tools. Please review the changed files format, and merge firstly. No local preview emporarily.

**Comment by kaikai1024** [comment]
Change the `translated_docs`  to check the preview.

**Comment by boundless-forest** [comment]
选区_059
选区_060

**Review by kaikai1024 — APPROVED** [review]

**Pull request merged**
