### PR TITLE
fix links

### PR DESCRIPTION
**Pull request by zhouyun-zoe**
修复循环跳转的问题

### CODE REVIEW

**Review by kaikai1024 — COMMENTED** [review]
rebase the latest master?
the rpc part

**Comment by zhouyun-zoe** [comment]
> rebase the latest master?
> the rpc part

Done

**Comment by kaikai1024** [comment]
> > rebase the latest master?
> > the rpc part
> 
> Done

still the same. the rpc part. check this #113

**Comment by kaikai1024** [comment]
another question: Do we need to update the translated_docs when i update cita doc, like #116

**Comment by zhouyun-zoe** [comment]
> another question: Do we need to update the translated_docs when i update cita doc, like #116

No. CI will auto update translated_docs after merging pr. Sometime I update translate_docs because I want to double-check in my localhost.

**Comment by kaikai1024** [comment]
> > another question: Do we need to update the translated_docs when i update cita doc, like #116
> 
> N�o. CI will auto update translated_docs after merging pr. Sometime I update translate_docs because I want to double-check in my localhost.

double-check? CI could be failed?
why not add the ci to this repo?

**Comment by zhouyun-zoe** [comment]
> > > another question: Do we need to update the translated_docs when i update cita doc, like #116
> > 
> > 
> > N�o. CI will auto update translated_docs after merging pr. Sometime I update translate_docs because I want to double-check in my localhost.
> 
> double-check? CI could be failed?
> why not add the ci to this repo?

CI would not failed. If you fix docs' content. There is no need to update translated docs. 
But when I fix infinite jump links, I need to check if it is fixed in both Chinese version and English version on my localhost since this issue caused by different reasons under different language.

**Review by kaikai1024 — APPROVED** [review]

**Pull request merged**
